

import {
    Person, Group, RecordVoiceOver, LocalLibrary, Gavel,
    Fingerprint, Functions, DeviceHub, AccountBalance, Domain, 
    Texture, Restaurant, VpnKey, Stars, Colorize, Android,
    Pets, LocalFlorist, LocationCity, Landscape, Place,
    Map as MapIcon, Waves, Visibility, Build, Loop, BrightnessLow,
    PanTool, Palette, Info,
} from '@material-ui/icons';

enum SubCategories {
    Biographies = 'biographies',
    Cultures = 'cultures',
    Linguistics = 'linguistics',
    Literature = 'literature',
    Politics = 'politics',
    Races = 'races',
    Science = 'science',
    Technology = 'technology',
    Theology = 'theology',
    Archiecture = 'architecture',
    Clothing = 'clothing',
    FoodAndDrink = 'food and drink',
    Objects = 'objects',
    SpecialItems = 'special items',
    Weapons = 'weapons',
    Behemoths = 'behemoths',
    Fauna = 'fauna',
    Flora = 'flora',
    Cities = 'cities',
    Mountains = 'mountains',
    Places = 'places',
    Regions = 'regions',
    WaterBodies = 'water bodies',
    TheAgeOfAwakening = 'the age of awakening',
    TheAgeOfBeginnings = 'the age of beginnings',
    TheAgeOfUncertainty = 'the age of uncertainty',
    TheAgeOfEmpires = 'the age of empires',
    TheAgeOfRaces = 'the age of races',
    TheAgeOfCreation = 'the age of creation',
    Resources = 'resources'
}

const SubCategoryIcons: { [key: string ]: any } = {
    Biographies: Person,
    Cultures: Group,
    Linguistics: RecordVoiceOver,
    Literature: LocalLibrary,
    Politics: Gavel,
    Races: Fingerprint,
    Science: Functions,
    Technology: DeviceHub,
    Theology: AccountBalance,
    Archiecture: Domain,
    Clothing: Texture,
    FoodAndDrink: Restaurant,
    Objects: VpnKey,
    SpecialItems: Stars,
    Weapons: Colorize,
    Behemoths: Android,
    Fauna: Pets,
    Flora: LocalFlorist,
    Cities: LocationCity,
    Mountains: Landscape,
    Places: Place,
    Regions: MapIcon,
    WaterBodies: Waves,
    TheAgeOfAwakening: Visibility,
    TheAgeOfBeginnings: Build,
    TheAgeOfUncertainty: Loop,
    TheAgeOfEmpires: BrightnessLow,
    TheAgeOfRaces: PanTool,
    TheAgeOfCreation: Palette,
    Resources: Info,
}

export { SubCategories, SubCategoryIcons };